apiVersion: v1
kind: ServiceAccount
metadata:
  name: alice
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob
  namespace: tenant-services
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: carol
  namespace: tenant-services
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dave
  namespace: kube-system